spring:
  application:
    name: transaction-begin

  datasource:
    url: jdbc:mysql://localhost:3306/transaction
    username: root
    password: Alifpass@49
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 9878